### Zajęcia 9

###### Numpy - wstęp
    Numpy jest to biblioteka do obsługi tablic, macierzy i podstawowej algebry liniowej. Podstawowym typem 
    obiektu w bibliotece NumPy jest ndarray (n - wymiarowa tablica). Macierze NumPy są szybsze i zajmują 
    mniej pamięci niż listy pythona. Zajmowana przez nie przestrzeń w pamięci jest ciągła.
    
    Muszą zawierać dane jednego typu.
    
    Funkcja np.array() przyjmuje jako argument listę, krotkę itp. i tworzy z niej tablicę ndarray.
    

In [5]:
import numpy as np # importowanie biblioteki NumPy
a = np.array([4,2,6]) # tworzenie macierzy NumPyjowskiej z listy
print(type(a))
print(a)

<class 'numpy.ndarray'>
[4 2 6]


###### Tablice wielowymiarowe
    Podanie listy list, krotki krotek itp. jako argument funkcji np.array() tworzy wielowymiarową tablicę.
    
    Funkcje np.zeros() i np.ones() tworzą n-wymiarową tablicę wypełnioną odpowiednio zerami i jedynkami, o 
    kształcie przesłanym jako argument w postaci krotki, listy, itp.
    
    Argument .ndim - przechowuje wymiar tablicy
    Argument .size - ilość elementów w tablicy
    Argument .shape - kształt tablicy (ilość rzędów, kolumn)
    
    Tablice 1D:
        * np.arrange(start, stop, step, dtype) - tworzy tablicę wypełnioną liczbami z podanego zakresu
        * np.linspace(start, stop, num) - tworzy tablicę o zadanym rozmiarze z równoodległymi wartościami 
          pomiędzy start i stop
        
    Tablice 2D:
        * np.eye(n,m) - tworzy macierz jednostkową o rozmiarze (n,m - wiersze, kolumny)
        * np.diag() - tworzy macierz diagonalną w oparciu o tablicę

In [6]:
# Tablice wielowymiarowe
import numpy as np
a = np.array([[1,5,6],[4,2,3]]) # Tworzenie tablicy z listy list

print(a)
print(a.ndim) # wymiar tablicy
print(a.shape) # kształt tablicy

b = np.ones((3,3)) # Tworzenie tablicy jedynek o wymiarach 3x3
print(b)

[[1 5 6]
 [4 2 3]]
2
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Tablice 1D
import numpy as np
print(np.arange(1,5,0.5)) # Tablica liczb od 1 do 5 co 0.5
print(np.linspace(1,5,5)) # Tablica liczb od 1 do 5, 5 liczb

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[1. 2. 3. 4. 5.]


In [10]:
# Tablice 2D
import numpy as np
print(np.eye(2)) # Tablica jednostkowa 2x2
print(np.diag([5,4,2])) # Tablica z diagonalą 5, 4 ,2

[[1. 0.]
 [0. 1.]]
[[5 0 0]
 [0 4 0]
 [0 0 2]]


###### Indeksowanie
    Odwołanie do elementu podobne jak w obiektach pythona. W przypadku tablic wielowymiarowych, dalsze wymiary 
    są podawane po przecinku a[0,5]. Wycinki tablic odwołują się do oryginalnej tablicy - modyfikacja zmienia 
    również tablicę.
    
    Wycinek tablicy można wywołać a[start:stop:step]; pozostawienie pustych argumentów indeksuje cały wymiar. 
    Można podać tablicę indekstów a[()]. 
    Wycinanie może też być dokonywane zdaniami logicznymi a[a==5]

In [12]:
# Odwoływanie się do elementu
import numpy as np
x = np.arange(10) # tablica od 0 do 9
y = np.copy(x)
y.shape = (2,5) # tablica od 0 do 9 w kształcie 2 wiersze po 5 liczb

print(x)
print(x[3]) # wypisz 4 element tablicy x
print(y)
print(y[1,3]) # wypisz 4 element z 2 rzędu tablicy y

[0 1 2 3 4 5 6 7 8 9]
3
[[0 1 2 3 4]
 [5 6 7 8 9]]
8


In [13]:
# Wycinki tablicy
import numpy as np
x = np.arange(10) # tablica od 0 do 9
y = np.copy(x)
y.shape = (2,5) # tablica od 0 do 9 w kształcie 2 wiersze po 5 liczb

print(y)
print("1: ", x[2:6:2]) # wypisz elementy z tablicy x od 2 do 6, co 2
print("2: ", y[([0,1],[1,4])]) # element z 1 wiersza 2 oraz z 2 wiersza 5
print("3: ", x[x>5]) # tylko elementy większe od 5

[[0 1 2 3 4]
 [5 6 7 8 9]]
1:  [2 4]
2:  [1 9]
3:  [6 7 8 9]


###### Operacje na tablicach
    Operatory dodawania/odejmowania/mnożenia/dzielenia działają na tablicach NumPy'a - gdy wymiary tablic się 
    nie zgadzają, operatory są rozszerzane na wszystkie wymiary.
    
    Transpozycja jest dokonywana metodą .transpose()
    Funkcja np.sum() zwraca sumę elementów podanej tablicy
    Moduł linalg zawiera operacje z algebry liniowej
    
    Uzgadnianie wymiarów, konkatenacja:
        * numpy.reshape(array, shape) - zmiana kształtu tablicy array; shape jest to int lub krotka intów
        * numpy.concatenate(arrays, axis) - łączy tablice podane jako sekwencja arrays, względem osi 
        * numpy.stack(arrays, axis) - łączy tablice podane jako sekwencja arrays, względem osi, lecz w 
          kolejnym wymiarze
        * np.hstack(arr), np.vstack(arr), np.dstack(arr) - łączą tablice podane jako krotka arr jak 
          concatenate, ale horyzontalnie, wertykalnie i względem trzeciego wymiaru
    
    Dzielenie tablic:
        > numpy.split(array, indices_or_sections, axis) - dzieli tablicę array wg kryteriów podanych w 
          indices_or_sections, względem osi axis.
            indices_or_sections może być int-em, wtedy tablica dzielona jest na int równych tablic, lub 
            tablicą 1-D z indeksami wg. których tablica ma zostać 'przecięta'
        > np.hsplit(arr, x), np.vsplit(arr, x), np.dsplit(arr, x) - dzielą tablicę arr na x tablic 
          horyzontalnie, wertykalnie i względem trzeciej osi

    Iloczyn skalarny:
        ~ dot(a, b, out=None) - jeżeli wektory to iloczyn skalarny (bez sprzęgania pierwszego argumentu);
          jeżeli macierze to iloczyn macierzowy; jeżeli tensory wyższego rzędu to zwinięcie przedostatniego 
          wymiaru a z ostatnim b
        ~ vdot(a, b) - iloczyn skalarny, jeżeli zespolone to pierwszy argument sprzężony; tablice 
          wielowymiarowe spłaszczane

In [14]:
# Operacje na tablicach
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.ones([3,3])

print("a+b: ",a+b) # suma dwóch tablic
print("a+10: ",a+10) # dodanie 10 do wszystkich elementów tablic

print(np.dot(b,a).transpose()) # transpozycja iloczynu skalarnego

a+b:  [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
a+10:  [[11 12 13]
 [14 15 16]
 [17 18 19]]
[[12. 12. 12.]
 [15. 15. 15.]
 [18. 18. 18.]]


In [17]:
# Uzgadnianie wymiarów
import numpy as np
x = np.arange(10)
y = np.reshape(x, (5,2)) # zmiana kształtu tablicy

print(y.shape, x.shape)
print(y)
print(x)

# concatentate
z = np.arange(10,20)
z = np.reshape(z,(5,2))
q1 = np.concatenate((y, z), 0)
q2 = np.concatenate((y, z), 1)
print(q1.shape,q1)
print(q2.shape,q2)


(5, 2) (10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
(10, 2) [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
(5, 4) [[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]]


###### Zadania:

I. Napisz program wytający użytkownika o dwa n-wymiarowe wektory, oraz pozwalający mu obliczyć sumę wektorów, ich długość oraz to czy są ortogonalne względem siebie.

numpy.linalg.norm() - funkcja zwracająca normę podanej macierzy lub wektora. 

In [18]:
import numpy as np

# wprowadzenie wektorów
a = input("Wpisz pierwszy wektor(format: x1,x2, ...,xn) ")
b = input("Wpisz drugi wektor(format: y1,y2, ...,yn) ")

# zamiana stringów na floaty
l1 = a.split(",")
l2 = b.split(",")
lb1 = []
lb2 = []
for i in l1:
    j = float(i)
    lb1.append(j)
for i in l2:
    j = float(i)
    lb2.append(j)

# powstanie i wypisanie wektorów
v1 = np.array(lb1)
v2 = np.array(lb2)
print("Pierwszy wektor: ",v1)
print("Drugi wektor: ",v2)

# suma wektorów
sum = v1+v2
print("Suma wektorów wynosi: ",sum)

# długość wektorów
print("Długość 1 wektora: ", np.linalg.norm(v1))
print("Długość 2 wektora: ", np.linalg.norm(v2))

# ortogonalność
orto = np.dot(v1,v2) # iloczyn skalarny
if orto == 0:
    print("Wektory są ortogonalne")
elif orto != 0:
    print("Wektory nie są ortogonalne")
else:
    print("Błąd")

Wpisz pierwszy wektor(format: x1,x2, ...,xn) 2,5
Wpisz drugi wektor(format: y1,y2, ...,yn) 1,4
Pierwszy wektor:  [2. 5.]
Drugi wektor:  [1. 4.]
Suma wektorów wynosi:  [3. 9.]
Długość 1 wektora:  5.385164807134504
Długość 2 wektora:  4.123105625617661
Wektory nie są ortogonalne
